
   
name: "Close Stale Issues"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"

jobs:
  cleanup:
    permissions:
      issues: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v3
      with:

        # Messages
        ancient-issue-message: "" # disabling ancient
        stale-issue-message: This issue has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-pr-message: This PR has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        
        # Labels
        stale-issue-label: closing-soon
        exempt-issue-label: no-autoclose
        stale-pr-label: closing-soon
        exempt-pr-label: no-autoclose
        response-requested-label: response-requested
        closed-for-staleness-label: closed-for-staleness

        # Issue timing
        days-before-stale: 14
        days-before-close: 7
        days-before-ancient: 365
        minimum-upvotes-to-exempt: 5

        # Misc Settings
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        loglevel: DEBUG
        dry-run: true
