name: "Label issues with no response"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */3 * * *"

jobs:
  cleanup:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 5
        days-before-close: -1
        exempt-issue-labels: 'needs-triage'
        exempt-pr-labels: 'needs-triage'
        stale-issue-label: 'needs-triage'
        operations-per-run: 250
        enable-statistics: true
        stale-issue-message: |
          This issue requires triage and should be assigned. 
        stale-pr-label: 'needs-triage'
        stale-pr-message: |
          PR requires assignment.
        debug-only: true
        exempt-all-milestones: true
